trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8100
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9100
    timeout: 1s
data:
  database:
    dsn: "root:123456@tcp(127.0.0.1:3306)/switch_data_center?charset=utf8mb4&parseTime=True&loc=UTC&multiStatements=true"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  key: eb8c144fc1bbc344e17652009fe3616f